### ISSUE TITLE
paperspigot 1.11.2?

### ISSUE THREAD

**Issue by haugsvar** [Eniripsa96/StopGen#1]
Can we have a build for paperspigot with nms v1_11_R1?

Alternatively, how can I build it myself?

**Comment by Eniripsa96** [comment]
It would require a bit of coding knowledge for you to modify and build it. If you have that sort of background, just pull down the code, reference Spigot, copy one of the versioned folders (likely the 1_9_R2 one) to one for 1.11, and change all the imports in that folder to point to 1_11_R1 instead of 1_9_R2, fixing any issues that pop up due to minecraft version differences.
